### PR TITLE
Changed the Algorithm 

### PR DESCRIPTION
**Pull request by dennism501**
I added a new random picking method and different iterator

### CODE REVIEW

**Review by k9uma — COMMENTED** [review]
How is this more efficient though?

**Comment by dennism501** [comment]
I went more for code optimization lookin at how it’s running multiple permutations. So 3 nested for loops will run at O(N^3) as opposed to a while loop which will run at O(1). Then with the 3 forloops, you are using them just to get the next index in the array list limit the number of combinations you will have, if you notice your iteration is stopping at some point. So randomizing it will run 6^3 times looking at the number of combinations to try and get to 30. It will I will only stop when 30 is found, but since it’s not possible. It will loop for infinite number of times

**Comment by k9uma** [comment]
> 
> 
> I went more for code optimization lookin at how it’s running multiple permutations. So 3 nested for loops will run at O(N^3) as opposed to a while loop which will run at O(1). Then with the 3 forloops, you are using them just to get the next index in the array list limit the number of combinations you will have, if you notice your iteration is stopping at some point. So randomizing it will run 6^3 times looking at the number of combinations to try and get to 30. It will I will only stop when 30 is found, but since it’s not possible. It will loop for infinite number of times

Lol so it will never end then, how do we break out of it?

**Review by k9uma — CHANGES_REQUESTED** [review]
Great change in algorithm but it needs to stop at some point.

**Comment by dennism501** [comment]
yeah it has to change, it has to stop. Let me continue looking at it later. I think setting a limit of how much permutations it has to do or just changing the algorithm all together

**Comment by dennism501** [comment]
For now my Algorithm is flawed, after reviewing it. The while statement is only checking for the answer to be 30, if that answer doesn't come. It will continue picking sets of 3 and repeating the process until it finds the answer 30. Since there is no answer, the loop will run infinitely. We can discard it for now

**Comment by k9uma** [comment]
> 
> 
> For now my Algorithm is flawed, after reviewing it. The while statement is only checking for the answer to be 30, if that answer doesn't come. It will continue picking sets of 3 and repeating the process until it finds the answer 30. Since there is no answer, the loop will run infinitely. We can discard it for now

Okay great, we can discuss it tomorrow at #Hacktoberfest

**Pull request closed without merging**
